version: 2
registries:
  ghcr-docker:
    type: docker-registry
    url: ghcr.io
    replaces-base: true
    username: ${{ secrets.T2_GHCR_USER }}
    password: ${{ secrets.T2_GHCR_PASSWORD }}
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
  - package-ecosystem: "docker"
    directory: /charts/set-version/
    registries:
      - ghcr-docker
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
