name: cookiecutter

on:
  workflow_dispatch:
  push:
      branches:
          - main

jobs:
  asdf-vm:
      runs-on: ubuntu-latest
      steps:
        - name: Install asdf on the Action Runner
          uses: asdf-vm/actions/setup@v4.0.0
          with:
            asdf_branch: "v0.14.1"

        - uses: actions/setup-python@v6
          with:
            python-version: '3.10'

        - uses: actions/checkout@v4

        - name: Install asdf tools
          working-directory: .
          run: |
            cp .tool-versions $HOME/
            asdf plugin-add terraform
            asdf plugin-add terraform-docs
            asdf plugin-add cookiecutter
            asdf plugin-add helm
            asdf install
