name: Create PR

on:
  workflow_dispatch:
    inputs:
      transcoder_version:
        required: true
        description: Version of the transcoder
        type: string

jobs:
  create:
    name: Create PR
    permissions:
      content: write
      pull-request: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b "v${{ inputs.transcoder_version }}"
          yq e -i '.transcoder_version.version = "${{ inputs.transcoder_version }}"' charts/set-version/version.yaml
          git add charts/set-version/version.yaml
          git commit -m "chore: update transcoder version ${{ inputs.transcoder_version }}"
          git push -u origin "v${{ inputs.transcoder_version }}"
          gh pr create --fill-first --base main --head "v${{ inputs.transcoder_version }}"
