name: Create PR

on:
  workflow_dispatch:
    inputs:
      transcoder_version:
        required: true
        description: Version of the transcoder
        type: string

jobs:
  create:
    name: Create PR
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Update version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_FILE: charts/set-version/version.yaml
          MESSAGE: "chore: update transcoder version ${{ inputs.transcoder_version }}"
        run: |
          yq e -i '.transcoder_version.version = "${{ inputs.transcoder_version }}"' $VERSION_FILE
          export CONTENT=$( base64 -i $VERSION_FILE )
          gh api --method POST /repos/${{ github.repository }}/git/refs \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --field ref=refs/heads/v${{ inputs.transcoder_version }} \
            --field sha=${{ github.sha }}
          export SHA=$( git rev-parse main:$VERSION_FILE )
          gh api --method PUT /repos/${{ github.repository }}/contents/$VERSION_FILE \
            --field message="chore: update transcoder version v${{ inputs.transcoder_version }}" \
            --field content="$CONTENT" \
            --field encoding="base64" \
            --field branch="v${{ inputs.transcoder_version }}" \
            --field sha=$SHA
          gh pr create \
            --base main \
            --head "v${{ inputs.transcoder_version }}" \
            --title "$MESSAGE" \
            --body "T2 Transcoder version update to v${{ inputs.transcoder_version }}"
