name: Force Success

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'chore/**'

jobs:
  fail:
    name: Fail
    runs-on: ubuntu-latest
    steps:
      - name: fail
        continue-on-error: true
        run: |-
          echo "This job is expected to fail"
          exit 1
      - name: check failure
        if: ${{ failure() }}
        run: echo "The previous step failed as expected"
