name: Force Success

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'chore/**'

jobs:
  fail:
    name: Fail
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: |-
          echo "This job is expected to fail"
          exit 1

  success:
    name: Succeed
    needs: fail
    runs-on: ubuntu-latest
    steps:
      - name: succeed
        run: echo "This job is expected to succeed"