name: Set Version

on:
  workflow_call:
    inputs:
      enable-semver:
        description: Flag to enable semantic versioning.
        type: boolean
        default: true
      enable-timestamp:
        description: Flag to enable timestamp-based versioning.
        type: boolean
        default: true
    outputs:
      version-tag:
        description: The version tag that was set.
        value: ${{ jobs.set-version.outputs.versiontag }}

permissions:
  contents: read

jobs:
  set-version:
    runs-on: ubuntu-latest
    outputs:
      versiontag: ${{ steps.meta.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            east-repo/app
            west-repo/app
          tags: |
            type=sha
            type=semver,enable=${{ inputs.enable-semver }},pattern={{raw}}
            type=raw,enable=${{ inputs.enable-timestamp }},prefix=0.0.,suffix=,value=${{ github.run_id }}
  print-version:
    needs: set-version
    runs-on: ubuntu-latest
    steps:
      - name: Print the version tag
        run: |
          echo "Version Tag: ${{ needs.set-version.outputs.versiontag }}"
