name: Set Version

on:
  workflow_call:
    inputs:
      enable-semver:
        description: Flag to enable semantic versioning.
        type: boolean
        default: false
      enable-timestamp:
        description: Flag to enable timestamp-based versioning.
        type: boolean
        default: false
    outputs:
      version-tag:
        description: The version tag that was set.
        value: ${{ jobs.set-version.outputs.versiontag }}

permissions:
  contents: read

jobs:
  set-version:
    runs-on: ubuntu-latest
    outputs:
      versiontag: ${{ steps.meta.outputs.tags }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            east-repo/app
            west-repo/app
          tags: |
            type=sha
            type=semver,enable=${{ inputs.enable-semver }},pattern={{raw}}

      - name: Show tags
        run: |
          echo ${{ steps.meta.outputs.tags }}
